"""Parser and manager for server.properties file."""

from pathlib import Path
from typing import Any


class ServerProperties:
    """
    Manager for Minecraft server.properties file.

    Provides read/write access to server configuration.
    """

    # Common properties with their types and descriptions
    KNOWN_PROPERTIES = {
        "server-port": ("int", "Server port (default: 25565)"),
        "max-players": ("int", "Maximum players (default: 20)"),
        "view-distance": ("int", "View distance in chunks (default: 10)"),
        "simulation-distance": ("int", "Simulation distance (default: 10)"),
        "motd": ("str", "Message of the day"),
        "level-name": ("str", "World folder name (default: world)"),
        "level-seed": ("str", "World seed"),
        "level-type": ("str", "World type (default, flat, etc.)"),
        "gamemode": ("str", "Default gamemode (survival, creative, etc.)"),
        "difficulty": ("str", "Difficulty (peaceful, easy, normal, hard)"),
        "hardcore": ("bool", "Hardcore mode"),
        "pvp": ("bool", "Allow PvP"),
        "spawn-monsters": ("bool", "Spawn monsters"),
        "spawn-animals": ("bool", "Spawn animals"),
        "spawn-npcs": ("bool", "Spawn villagers"),
        "allow-flight": ("bool", "Allow flight"),
        "allow-nether": ("bool", "Allow Nether"),
        "force-gamemode": ("bool", "Force default gamemode"),
        "white-list": ("bool", "Enable whitelist"),
        "enforce-whitelist": ("bool", "Kick non-whitelisted on reload"),
        "online-mode": ("bool", "Verify player accounts (keep true!)"),
        "enable-command-block": ("bool", "Enable command blocks"),
        "enable-rcon": ("bool", "Enable RCON"),
        "rcon.port": ("int", "RCON port"),
        "rcon.password": ("str", "RCON password"),
        "enable-query": ("bool", "Enable query"),
        "query.port": ("int", "Query port"),
        "server-ip": ("str", "Server bind IP (empty = all)"),
        "resource-pack": ("str", "Resource pack URL"),
        "resource-pack-sha1": ("str", "Resource pack hash"),
        "player-idle-timeout": ("int", "AFK kick timeout (0 = disabled)"),
        "max-world-size": ("int", "Maximum world radius"),
        "rate-limit": ("int", "Packet rate limit"),
        "spawn-protection": ("int", "Spawn protection radius"),
        "op-permission-level": ("int", "Default op permission level (1-4)"),
        "function-permission-level": ("int", "Function permission level"),
        "max-tick-time": ("int", "Max tick time before watchdog (ms)"),
        "network-compression-threshold": ("int", "Compression threshold"),
        "sync-chunk-writes": ("bool", "Sync chunk writes"),
        "enable-jmx-monitoring": ("bool", "Enable JMX"),
        "enable-status": ("bool", "Show in server list"),
        "hide-online-players": ("bool", "Hide player list"),
        "entity-broadcast-range-percentage": ("int", "Entity visibility range %"),
        "text-filtering-config": ("str", "Text filter config"),
        "log-ips": ("bool", "Log player IPs"),
        "use-native-transport": ("bool", "Use native transport"),
        "previews-chat": ("bool", "Chat previews"),
        "enforce-secure-profile": ("bool", "Enforce signed chat"),
    }

    def __init__(self, path: Path):
        """
        Initialize with path to server.properties.

        Args:
            path: Path to server.properties file
        """
        self.path = path
        self._properties: dict[str, str] = {}
        self._comments: list[str] = []

    def load(self) -> None:
        """Load properties from file."""
        self._properties.clear()
        self._comments.clear()

        if not self.path.exists():
            return

        with open(self.path, encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n\r")

                # Comment or blank line
                if not line or line.startswith("#"):
                    self._comments.append(line)
                    continue

                # Property line
                if "=" in line:
                    key, _, value = line.partition("=")
                    self._properties[key.strip()] = value.strip()

    def save(self) -> None:
        """Save properties to file."""
        self.path.parent.mkdir(parents=True, exist_ok=True)

        lines = []

        # Add header comment
        lines.append("#Minecraft server properties")
        lines.append("#Generated by Minecraft Server Manager")
        lines.append("")

        # Write properties
        for key, value in sorted(self._properties.items()):
            lines.append(f"{key}={value}")

        with open(self.path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            f.write("\n")

    def get(self, key: str, default: Any = None) -> Any:
        """
        Get a property value with type conversion.

        Args:
            key: Property key
            default: Default value if not found

        Returns:
            Property value converted to appropriate type
        """
        if key not in self._properties:
            return default

        value = self._properties[key]

        # Get expected type
        prop_info = self.KNOWN_PROPERTIES.get(key)
        if prop_info:
            prop_type = prop_info[0]
            if prop_type == "bool":
                return value.lower() == "true"
            elif prop_type == "int":
                try:
                    return int(value)
                except ValueError:
                    return default

        return value

    def set(self, key: str, value: Any) -> None:
        """
        Set a property value.

        Args:
            key: Property key
            value: Value to set (will be converted to string)
        """
        if isinstance(value, bool):
            self._properties[key] = "true" if value else "false"
        else:
            self._properties[key] = str(value)

    def get_raw(self, key: str) -> str | None:
        """Get raw string value of a property."""
        return self._properties.get(key)

    def __getitem__(self, key: str) -> Any:
        """Get property using dict syntax."""
        return self.get(key)

    def __setitem__(self, key: str, value: Any) -> None:
        """Set property using dict syntax."""
        self.set(key, value)

    def __contains__(self, key: str) -> bool:
        """Check if property exists."""
        return key in self._properties

    def keys(self) -> list[str]:
        """Get all property keys."""
        return list(self._properties.keys())

    def items(self) -> list[tuple[str, str]]:
        """Get all property key-value pairs."""
        return list(self._properties.items())

    def update_for_manager(
        self,
        rcon_port: int,
        rcon_password: str,
        server_port: int = 25565,
    ) -> None:
        """
        Update properties required for the manager to work.

        Enables RCON and sets the required ports/passwords.

        Args:
            rcon_port: RCON port
            rcon_password: RCON password
            server_port: Server port
        """
        self.set("enable-rcon", True)
        self.set("rcon.port", rcon_port)
        self.set("rcon.password", rcon_password)
        self.set("server-port", server_port)
        # Recommended settings
        self.set("enable-query", False)
        self.set("sync-chunk-writes", True)

    @classmethod
    def create_default(
        cls,
        path: Path,
        server_port: int = 25565,
        rcon_port: int = 25575,
        rcon_password: str = "",
        motd: str = "A Minecraft Server",
    ) -> "ServerProperties":
        """
        Create a new server.properties with default values.

        Args:
            path: Path to save the file
            server_port: Server port
            rcon_port: RCON port
            rcon_password: RCON password
            motd: Message of the day

        Returns:
            Configured ServerProperties instance
        """
        props = cls(path)

        # Set defaults
        props.set("server-port", server_port)
        props.set("max-players", 20)
        props.set("motd", motd)
        props.set("view-distance", 10)
        props.set("simulation-distance", 10)
        props.set("level-name", "world")
        props.set("gamemode", "survival")
        props.set("difficulty", "normal")
        props.set("hardcore", False)
        props.set("pvp", True)
        props.set("spawn-monsters", True)
        props.set("spawn-animals", True)
        props.set("spawn-npcs", True)
        props.set("allow-flight", False)
        props.set("allow-nether", True)
        props.set("white-list", False)
        props.set("online-mode", True)
        props.set("enable-command-block", False)

        # RCON settings
        props.set("enable-rcon", True)
        props.set("rcon.port", rcon_port)
        props.set("rcon.password", rcon_password)

        props.save()
        return props
